Feature/junwoo layered patteren products
wecode-bootcamp-korea/42-1st-TeaTalk-backend pull request #6
Opened 2023-02-10 06:54 UTC by Indobobusang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성

- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성

- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지

1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항

- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-02-13 02:32 UTC, sangwoong03 requested changes
고생하셨습니다. 준우님

쿼리빌더와 관련된 내용이 많이 어려우셨을 텐데 오늘 진행되는 세션도 참고하셔서 잘 구현해보셨으면 좋겠습니다!

2023-02-13 02:32 UTC, sangwoong03 commented on models/datasource.js
> +    console.log("Failed to connect database");
해당 코드는 은경님 PR에 리뷰 남긴 사항을 확인해주세요~!
[링크이동](https://github.com/wecode-bootcamp-korea/42-1st-TeaTalk-backend/pull/5#discussion_r1102358346)

2023-02-13 02:32 UTC, sangwoong03 commented on routes/productRouter.js
> +router.get("/list", productController.allProducts);
RESTful API를 설계하는 데 있어, 이미 index.js 파일에서 `/products`라는 리소를 명시하고 있기 때문에 `list`라는 리소스를 명시하지 않아도 될 것 같습니다.
```suggestion
router.get("/", productController.allProducts);
```

2023-02-13 02:32 UTC, sangwoong03 commented on controllers/productController.js
> +  const sort = pageInfo.sort;
- 4~6번 라인의 코드는 페이지네이션 구현을 위한 query parameter로 보입니다.
페이지네이션을 구현할 때 LIMIT 구문을 잘 사용해주셨는데요, LIMIT과 OFFSET에 해당하는 데이터는 pageInfo라는 객체에 별도의 key: value 형태로 안받아도 될 것 같습니다!
프론트엔드 개발자들과 다시 논의하여 limit과 offset이라는 key에 페이지에 대한 number 데이터만 받아와도 될 것 같습니다.

- 나머지 데이터 구조분해할당을 통해 데이터를 받아오면 조금 더 간결하게 코드를 작성할 수 있을 것으로 보입니다.
아래 예시 코드를 참고해주세요!

 ```suggestion
  const { category, subCategory, type, sort, limit, offset } = req.query
  const productType = type ? type.split(",") ; ""; // 해당 코드는 service 단에서 다루는 것이 좋을 것 같습니다!
```

2023-02-13 02:32 UTC, sangwoong03 commented on controllers/productController.js
> +      return res.status(404).json({ message: "Page_ERROR" });
해당 API 내부에서는 query parameter로 받아오는 limit, offset 데이터는 특정 유저가 이미 화면에 보이는 페이지 번호를 클릭했을 때 해당 번호가 백엔드 서버에 들어옵니다.

페이지네이션 범위를 벗어나는 limit offset 값을 요청한 경우에만 `page error`를 반환하는 것이 좋아보입니다.

반대로 limit과 offset데이터가 없는 경우에는 default 값을 설정하여 첫페이지 혹은 전체데이터를 보여주면 좋을 것 같습니다.

2023-02-13 02:32 UTC, sangwoong03 commented on models/productDao.js
> +};
제품의 전체 개수를 조회하는 쿼리문입니다.
- 우선 함수명이 함수의 행위와 예측 결과가 포함되면 좋을 것 같습니다.
- `*` 와일드카드를 사용하여 전체 컬럼을 조회하는 것보다 단순 개수를 세기 위해 id 컬럼만 추가해주는 것이 좋을 것 같습니다.
- Alias (별칭)을 통해 외부에서 해당 함수의 결과를 호출할 때 `result.counts` 등과 같이 접근할 수 있게 하면 좋을 것 같습니다.  
```suggestion
const getProductCounts = async () => {
  return await teaDataSource.query(
    `SELECT
      count(id) as counts
    FROM
    products`
  );
};
```

2023-02-13 02:32 UTC, sangwoong03 commented on services/productService.js
> +  }
limit과 offset에 대해 클라이언트가 요청하는 데이터가 없다면 매개변수에서 deafultValue를 설정해줄 수 있습니다. 
만약 데이터가 들어온다면 deafultValue 대신 클라이언트가 요청한 데이터로 치환되어 각 레이어에 전달됩니다.

```suggestion
const allProducts = async (category, subCategory, type, sort, limit=15, offset=0) => {
```

2023-02-13 02:32 UTC, sangwoong03 commented on services/productService.js
> +  }
Dao 함수명 수정에 따라 해당 부분도 변수, 함수명 수정해주세요~!
```suggestion
  const productCounts = await productDao.getProductsCounts();
  if (page > Math.ceil(productCounts.counts / pageSize)) {
    const err = new Error("제품이 없습니다.");
    err.statusCode = 400;
    throw err;
  }
```

2023-02-13 02:32 UTC, sangwoong03 commented on services/productService.js
> +};
마이너하지만 변수명 수정해주면 좋을 것 같습니다~!
결과 자체만 보면 products 리스트가 반환되기 때문입니다.
```suggestion
  // 혹은 products 
  const result = await productDao.getProduct(
    start,
    pageSize,
    category,
    sub,
    type,
    sort
  );
  return result;
};
```

2023-02-13 02:32 UTC, sangwoong03 commented on services/productService.js
> +const allProducts = async (page, pageSize, category, sub, type, sort) => {
해당 함수는 상품을 조회하는 코드를 포괄하는 함수이기 때문에 함수명이 다음과 같다면 더 좋을 것 같습니다.
 ```suggestion
const getProducts = async (page, pageSize, category, sub, type, sort) => {
```

2023-02-13 02:32 UTC, sangwoong03 commented on models/productDao.js
> +    : "";
우선 삼항연산자를 쓰는 이유는 다음과 같습니다:
- 조건문의 조건이 짧고 `if ... else ...`로 조건이 분기처리되는 경우 if else 문을 사용하지 않고 더 간결하게 작성하기 위해

하지만, 지금 삼항연산자를 통해 더욱 더 가독성이 떨어지고 있는 것 같습니다.

그렇기 때문에 저번주에 간략하게 언급드린 `Query builder`를 사용하게 됩니다.
쿼리 빌더는 함수로 혹은 객체 매핑을 통해 구현할 수 있습니다. (세부 사항은 13일 월요일 쿼리 빌더 세션 간 전달 예정)
쿼리 빌더는 Data Access Layere에서 사용되는 raw query문을 반환하기 때문에 서비스 로직 혹은 각 dao 파일에서 작성해도 되고, 쿼리 빌더가 길어지는 경우 하나의 모듈로 분리할 수도 있으니 참고해주세요! :)


예시는 다음과 같습니다:

```suggestion
  let conditionClause = "";
  
  if ( categoryCondition) {
    conditionCluase += `WHERE c.name = ${category}`;
  }
```

2023-02-13 02:32 UTC, sangwoong03 commented on models/productDao.js
> +  }
객체를 통해 매핑하는 방법은 다음과 같이 적을 수 있습니다:
`sortSet`이라는 객체의 key 값으로 클라이언트가 요청하는 sort value를 적어줍니다.
만약 클라이언트가 요청하는 sort value가 sortSet의 key값으로 있다면 ( == `sortSet[sort]`) 해당 쿼리문이 변수에 할당되도록 구현할 수 있습니다.


```suggestion
  const sortSet = {
    new_arrival: "ORDER BY p.created_at DESC",
    price_desc: "ORDER BY p.discount_price DESC",
    price_asc: "ORDER BY p.discount_price ASC",
  };
  
  const sortCondition = sortSet[sort];
```

2023-02-15 01:21 UTC, sangwoong03 reviewed
해당 PR은 이따 구두로 리뷰드릴게요.
컨플릭트 우선 해결해주세요.

2023-02-15 07:14 UTC, sangwoong03 requested changes

2023-02-15 07:14 UTC, sangwoong03 commented on app.js
> +const routes = require("./routes");
모듈을 import 하는 부분이기 때문에 아래 코드와 공백을 두어 구분을 해주세요~!

2023-02-15 07:14 UTC, sangwoong03 commented on controllers/productController.js
> +  const limit = 12;
limit 값이 고정되어 있다면, sql query 상에서 값을 직접 넣어주어도 될 것 같습니다!

2023-02-15 07:14 UTC, sangwoong03 commented on controllers/productController.js
> +  const { category, sub, type, sort, offset = 1 } = req.query;
- offset을 1로 설정했을 때 첫번째 row 데이터부터 나오는 지 확인해주세요~
- category와 sub라는 key(변수)가 무엇을 가리키는 지 조금 애매한 것 같습니다. 명확하게 작성해주세요!
```suggestion
  const { categoryId, subCategoryId, type, sort, offset = 1 } = req.query;
```

2023-02-15 07:14 UTC, sangwoong03 commented on services/productService.js
> +  let start = 0;
query문의 `LIMIT` 구문에서 start 변수를 사용하나요 아니면 offset 변수를 사용하나요?

확인 후 수정해주세요~!

2023-02-15 07:14 UTC, sangwoong03 commented on models/productDao.js
> +  }
위의 코드와 구분만 해주면 좋을 것 같습니다~!

2023-02-15 07:19 UTC, sangwoong03 requested changes

2023-02-15 07:19 UTC, sangwoong03 commented on models/productDao.js
> +    [start, limit]
- 포매팅 수정해주세요!
- product id 값도 반환해주세요!
```suggestion
    `SELECT
        p.name,
        p.price,
        p.discount_price
      FROM  products AS p
      INNER JOIN subcategories AS s ON p.subcategory_id = s.id
      INNER JOIN categories AS c ON s.category_id = c.id
      ${typeCondition}
      ${whereCondition}
      ${categoryCondition}
      ${subCondition}
      ${andCondition}
      ${typeArrCondition}
      ${sortCondition}
      LIMIT ?,?`,
    [start, limit]
```

2023-02-15 08:24 UTC, sangwoong03 requested changes
준우님 리뷰 반영이 잘 안된 것 같습니다.

추가로 불필요한 `console.log()`코드 삭제해주시고, conflict도 해결해주세요!

2023-02-15 11:03 UTC, sangwoong03 requested changes

2023-02-15 11:03 UTC, sangwoong03 commented on Services/productService.js
> +const getProductList = async (
Service 폴더가 맞는지, service 폴더가 맞는지 다시 한번 꼼꼼하게 확인 후 push 해주세요

main 브랜치에도 service 폴더와 Service 폴더 두개가 있습니다.

2023-02-15 11:03 UTC, sangwoong03 commented on Services/productService.js
> +  const limit = 12;
SQL 쿼리문에 LIMIT에 대한 값이 설정되어 있습니다.
해당 변수는 불필요해보이니 삭제해주세요.

2023-02-15 11:03 UTC, sangwoong03 commented on Services/productService.js
> +  }
- productDao 함수의 매개변수를 설정할 때 `offset`에 대한 기본 값을 설정해주세요.
- **offset을 0으로 설정했을 때와 1로 설정했을 때의 결과 값을 보여주는 화면을 커멘트에 작성해주세요**
```javascript
const getProduct = async (offset=0 , ... ) => {}
```

2023-02-15 11:03 UTC, sangwoong03 commented on models/productDao.js
> +  start,
- start(offset)에 대한 기본값 설정해주세요
```suggestion
  start = 0,
```

2023-02-15 11:18 UTC, Indobobusang commented on Services/productService.js
> +const getProductList = async (
넵..

2023-02-15 11:42 UTC, Indobobusang commented on Services/productService.js
> +  }
<img width="1332" alt="스크린샷 2023-02-15 오후 8 39 40" src="https://user-images.githubusercontent.com/120322181/219018004-c097d5af-5359-458e-98ea-663e03b1a8f6.png">
<img width="1392" alt="스크린샷 2023-02-15 오후 8 40 10" src="https://user-images.githubusercontent.com/120322181/219018025-e3b2c958-68ce-4045-b784-2f57f68e68ce.png">
<img width="1392" alt="스크린샷 2023-02-15 오후 8 40 24" src="https://user-images.githubusercontent.com/120322181/219018038-928103b5-3b30-43d2-96ed-32da74a21bb2.png">

2023-02-16 00:17 UTC, sangwoong03 requested changes

2023-02-16 00:17 UTC, sangwoong03 commented on Services/productService.js
> +const getProductList = async (
반영이 안되어있습니다. 확인 다시 해주세요~

2023-02-16 05:56 UTC, closed without merging