Feature/carts
wecode-bootcamp-korea/42-1st-TeaTalk-backend pull request #8
Opened 2023-02-13 14:25 UTC by Indobobusang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성

- 장바구니 조회, 장바구니에 제품 추가, 장바구니에서 제품 수량 업데이트, 장바구니에서 제품 지우기 기능 구현 

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성

- 장바구니 조회, 장바구니에 제품 추가, 장바구니에서 제품 수량 업데이트, 장바구니에서 제품 지우기 기능 구현 

<br />

## :: 테스트 결과 이미지
1.  Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="1392" alt="스크린샷 2023-02-13 오후 11 23 09" src="https://user-images.githubusercontent.com/120322181/218484045-b3e9a46b-a4d6-4f33-ad44-78d24ecf7ff7.png">
<img width="1392" alt="스크린샷 2023-02-13 오후 11 23 20" src="https://user-images.githubusercontent.com/120322181/218484111-8fe097c0-948f-4f42-9c37-cc3130f27ab0.png">
<img width="1392" alt="스크린샷 2023-02-13 오후 11 23 27" src="https://user-images.githubusercontent.com/120322181/218484136-51700eeb-bd27-40b5-8d1b-31aa8d071232.png">

<br />

## :: 기타 질문 및 특이 사항

- 장바구니에 더 필요한 기능이 있을까요?

2023-02-14 01:49 UTC, sangwoong03 requested changes

2023-02-14 01:49 UTC, sangwoong03 commented on controllers/cartController.js
> +const cartIn = async (req, res) => {
가이드 드렸던 사항과 동일한데요, 함수명 한번 더 고려해서 작성해보세요~!

2023-02-14 01:49 UTC, sangwoong03 commented on routes/cartRouter.js
> +router.get("/:userId", cartController.showCart);
userId는 토큰 정보에서 확인할 수 있기 때문에 path parameter로 확인하지 않아도 됩니다.

또한, path parameter로 `userId` 정보를 요청 받아 처리할 경우, 제 3자가 userId 값만 가지고 악의적인 요청을 할 가능성이 발생할 수도 있습니다.

validateToken 모듈을 새로 생성하여 userId가 필요한 엔드포인트에서 미들웨어로 사용할 수 있도록 수정해주세요.

2023-02-14 01:49 UTC, sangwoong03 commented on models/datasource.js
> +};
이미 main 브랜치에 `datasource.js` 파일이 존재합니다.

해당 파일을 수정하는 것이 아니라면, 새롭게 추가하는 코드는 불필요해보이니 github 상에서 push되지 않도록 수정해주세요.

2023-02-14 01:49 UTC, sangwoong03 commented on controllers/cartController.js
> +const showCart = async (req, res) => {
가이드 드렸던 사항과 동일한데요, 함수명 한번 더 고려해서 작성해보세요~!

2023-02-14 01:49 UTC, sangwoong03 commented on controllers/cartController.js
> +  const { userId } = req.params;
router 리뷰 내용과 동일합니다.
userId는 토큰에 포함되어 있기 때문에 토큰의 payload 정보에서 userId 값을 받아오는 모듈이 필요합니다.

2023-02-14 01:49 UTC, sangwoong03 commented on controllers/cartController.js
> +    const { userId, productId, quantity } = req.body;
router 리뷰 내용과 동일합니다.
userId는 토큰에 포함되어 있기 때문에 토큰의 payload 정보에서 userId 값을 받아오는 모듈이 필요합니다.

2023-02-14 01:49 UTC, sangwoong03 commented on controllers/cartController.js
> +    const cart = await cartService.cartIn(userId, productId, quantity);
cart라는 변수를 사용하지 않기 때문에 장바구니를 새로 생성하는 service 함수의 결과를 변수에 할당하지 않아도 될 것 같습니다.
```suggestion
    await cartService.cartIn(userId, productId, quantity);
```

2023-02-14 01:49 UTC, sangwoong03 commented on controllers/cartController.js
> +    } else {
해당 로직은 클라이언트가 처리해도 되는 로직으로 보이네요.

백엔드 서버에서 `상품이 없다`는 메시지를 반환해도 좋지만, 그 결과값 자체가 `빈 배열 [ ]`이라면 프론트엔드 개발자들이 그 배열의 길이에 따른 로직을 처리하기가 더 쉬울 것 같습니다.

2023-02-14 01:49 UTC, sangwoong03 commented on controllers/cartController.js
> +  const { userId, cartId } = req.body;
router 리뷰 내용과 동일합니다.
userId는 토큰에 포함되어 있기 때문에 토큰의 payload 정보에서 userId 값을 받아오는 모듈이 필요합니다.

2023-02-14 01:49 UTC, sangwoong03 commented on controllers/cartController.js
> +  }
해당 로직은 클라이언트가 처리해도 되는 로직으로 보이네요.

백엔드 서버에서 상품이 없다는 메시지를 반환해도 좋지만, 그 결과값 자체가 빈 배열 [ ]이라면 프론트엔드 개발자들이 그 배열의 길이에 따른 로직을 처리하기가 더 쉬울 것 같습니다.

2023-02-14 01:49 UTC, sangwoong03 commented on services/cartService.js
> +};
service 레이어에서도 함수명 다시 한번 고려해주세요~!

2023-02-14 01:49 UTC, sangwoong03 commented on models/cartDao.js
> +    [userId, productId, quantity, quantity]
포매팅 수정 한번 해주세요~!
```suggestion
    `INSERT INTO 
      carts (
      user_id,
      product_id,
      quantity
      )
      VALUE (
        ?,
        ?,
        ?
      ) ON DUPLICATE KEY UPDATE quantity = quantity + ?;`,
    [userId, productId, quantity, quantity]
```

2023-02-14 01:49 UTC, sangwoong03 commented on models/cartDao.js
> +    [userId]
포매팅 수정 한번 해주세요!~
```suggestion
    `SELECT
      p.name,
      c.quantity,
      p.discount_price,
      p.image_url
    FROM carts c
    INNER JOIN users u ON c.user_id = u.id
    INNER JOIN products p ON c.product_id = p.id
    WHERE u.id = ?;`,
    [userId]
```

2023-02-14 01:49 UTC, sangwoong03 commented on models/cartDao.js
> +  console.log(cartId);
- 해당 부분에서 작성해주신 반복문 로직도 쿼리빌더라고 할 수 있습니다. 잘 작성해주셨습니다. 조금 더 나은 방향성에 대해서는 이따 구두로 전달드리도록 하겠습니다~!

- `console.log()` 코드는 main 브랜치 merge 이후에 에러에 대한 로그 혹은 특정 로그를 확인하는 코드가 아니라면 삭제해주세요.

2023-02-14 01:49 UTC, sangwoong03 commented on models/cartDao.js
> +    [userId]
해당 부분도 다음과 같이 수정해볼 수 있습니다.
IN ... 구문을 사용한다면 이미 우리가 받아온 cartIdArr를 따로 가공하지 않고 바로 사용할 수 있습니다.
```suggestion
    `DELETE FROM
      carts c
      WHERE
      c.user_id = ?
      AND c.id IN ( ? ) ;`,
    [ userId, cartIdArr ]
```

2023-02-15 01:28 UTC, sangwoong03 reviewed
토큰 검증하는 미들웨어 추가 후 다시 push해주세요.

2023-02-15 01:28 UTC, sangwoong03 commented on models/userDao.js
> +    console.log("메롱-------------------------");
삭제

2023-02-15 01:36 UTC, Indobobusang commented on models/userDao.js
> +    console.log("메롱-------------------------");
죄송합니다...

2023-02-15 05:58 UTC, sangwoong03 commented on controllers/cartController.js
> +    if (!userId || !productId || !quantity) {
userId 예외처리는 validateToken 미들웨어에서 이미 처리하고 있습니다.

삭제해주세요.

2023-02-15 05:58 UTC, sangwoong03 commented on controllers/cartController.js
> +    }
해당 부분도 마찬가지로, userId 예외처리는 validateToken 미들웨어에서 이미 처리하고 있습니다.

삭제해주세요.

2023-02-15 06:37 UTC, sangwoong03 requested changes

2023-02-15 06:37 UTC, sangwoong03 commented on controllers/cartController.js
> +  const userId = req.user;
try 구문 안에서 선언하고 할당하도록 수정해주세요.

2023-02-15 06:37 UTC, sangwoong03 commented on middlewares/auth.js
> +    );
```suggestion
    const SECRET_KEY = process.env.SECRET_KEY;
    const decode = jwt.verify(token, SECRET_KEY);
```

2023-02-15 06:37 UTC, sangwoong03 commented on controllers/cartController.js
> +const showCartOfUser = async (req, res) => {
이런 함수명은 어떤가요 ?
```suggestion
const getCartsByUserId = async (req, res) => {
```

2023-02-15 08:01 UTC, sangwoong03 requested changes

2023-02-15 08:01 UTC, sangwoong03 commented on middlewares/auth.js
> +    next();
return 키워드를 통해 해당 함수가 종료됨을 표현할 수 있습니다.
추가로 next() 함수 이후의 예기치 못한 코드 실행을 방지할 수 있습니다.
```suggestion
    return next();
```

2023-02-15 08:01 UTC, sangwoong03 commented on controllers/cartController.js
> +      const err = new Error("Invalid quantity");
해당 메시지를 받았을 때 클라이언트는 `quantity`값만 잘못보냈다고 혼동할 수 있을 것 같습니다.

조건문에 따라 명확한 에러 메시지를 전달할 수 있도록 수정해주세요~!

2023-02-15 09:00 UTC, sangwoong03 requested changes
컨플릭트 해결해주세요~

2023-02-16 00:24 UTC, sangwoong03 approved these changes
LGTM 👍

2023-02-16 00:24 UTC, merged